---
http_interactions:
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.1p111
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '154'
      Date:
      - Thu, 06 Jul 2017 10:58:11 GMT
      Set-Cookie:
      - a054b5d9e987bf679f10c9d29be39478=dca83a65476ba479e1cba709dfada9ed; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAA3MvQ7CIBiF4XthFsJfK3Fr1aqDizTulH5NSIA2QF2M9y7TWZ7zftETSnI2a0gfZwGdkB6713i9oAN6hM1DgFhMcWvEb0i5biWU8JYwMrhofHX97nzBQ1oDvrmC9b1jFclmYlJZJSTMLadMLawRlgumjpOUojUgOVUL1MDZ5GzinEy97Rv6/QHfcrqrlgAAAA==
    http_version:
  recorded_at: Thu, 06 Jul 2017 10:58:11 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.1p111
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '154'
      Date:
      - Thu, 06 Jul 2017 10:58:11 GMT
      Set-Cookie:
      - a054b5d9e987bf679f10c9d29be39478=dca83a65476ba479e1cba709dfada9ed; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAA3MvQ7CIBiF4XthFsJfK3Fr1aqDizTulH5NSIA2QF2M9y7TWZ7zftETSnI2a0gfZwGdkB6713i9oAN6hM1DgFhMcWvEb0i5biWU8JYwMrhofHX97nzBQ1oDvrmC9b1jFclmYlJZJSTMLadMLawRlgumjpOUojUgOVUL1MDZ5GzinEy97Rv6/QHfcrqrlgAAAA==
    http_version:
  recorded_at: Thu, 06 Jul 2017 10:58:11 GMT
recorded_with: VCR 3.0.3
