---
http_interactions:
- request:
    method: get
    uri: https://prometheus.example.com/api/v1/query?query=ALL
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer good_token
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Length:
      - '63'
      Content-Type:
      - application/json
      Date:
      - Tue, 29 Aug 2017 07:16:16 GMT
      Gap-Auth:
      - system:serviceaccount:management-infra:management-admin@cluster.local
      Gap-Upstream-Address:
      - localhost:9090
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=5a1c127a070a4ed5f092c7a5867ad054; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[]}}'
    http_version:
  recorded_at: Tue, 29 Aug 2017 07:16:16 GMT
recorded_with: VCR 3.0.3
